name: Laravel CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check DNS resolution
      run: nslookup ${{ secrets.HOST }}
      
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/gudangku.web.id/html
          git pull origin main
          git status
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          chmod -R 777 storage bootstrap/cache
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          php artisan optimize
