name: Laravel CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check DNS resolution
      run: nslookup ${{ secrets.HOST }}
      
    - name: Deploy using SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          git config --global --add safe.directory /var/www/gudangku.web.id/html
          cd /var/www/gudangku.web.id/html
          git pull origin main
          composer install --no-interaction --prefer-dist --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          sudo chown -R $USER:$USER /var/www/gudangku.web.id/html
          chmod -R 775 storage
          chmod -R 775 bootstrap/cache
